site_name: Kepler
theme:
  palette:
    primary: teal
  name: material
  logo: logo.png
  language: en
  custom_dir: overrides
  features:
    - navigation.footer
    - toc.integrate

  highlightjs: true
  hljs_languages:
    - yaml
    - rust

docs_dir: ./docs
nav:
  - Home: index.md
  - Kepler:
      - Getting Started:
          - Installation Guide: kepler/installation/guide.md
      - Concepts/Guides:
          - Power Attribution: kepler/usage/power-attribution.md
      - Reference:
          - Configuration: kepler/usage/configuration.md
          - Metrics: kepler/design/metrics.md
      - Developer:
          - Guides: kepler/developer/dev-docs.md
  - Kepler Operator:
      - Getting Started:
          - OpenShift: kepler-operator/installation/openshift.md
  - Project:
      - Adopters: project/adopters.md
      - Resources: project/resources.md
      - Contributing: project/contributing.md
      - Support: project/support.md
  - Archive (v0.9.0 and below):
      - Overview: archive/README.md
      - Design (Legacy):
          - archive/design/architecture.md
          - archive/design/power_model.md
          - archive/design/metrics.md
          - archive/design/ebpf_in_kepler.md
          - archive/design/kepler-energy-sources.md
      - Installation (Legacy):
          - archive/installation/strategy.md
          - archive/installation/local-cluster.md
          - archive/installation/kepler.md
          - archive/installation/kepler-helm.md
          - archive/installation/community-operator.md
          - archive/installation/kepler-operator.md
          - archive/installation/kepler-rpm.md
          - archive/installation/Kepler-Telegraf-integration-steps.md
      - Usage (Legacy):
          - archive/usage/kepler_daemon.md
          - archive/usage/trouble_shooting.md
          - archive/usage/deep_dive.md
      - Hardware Engagement (Legacy):
          - archive/hardwareengagement/index.md
      - Kepler Model Server (Legacy):
          - Compatibility Notice: model-server-compatibility.md
          - archive/kepler_model_server/get_started.md
          - archive/kepler_model_server/architecture.md
          - archive/kepler_model_server/pipeline.md
          - archive/kepler_model_server/node_profile.md
          - archive/kepler_model_server/power_estimation.md
          - archive/kepler_model_server/api.md

markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:
  version: v0.4

plugins:
  - search:
      lang:
        - en
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
