'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: pip install -e .
      - uses: pkgxdev/setup@v1
        with:
          +: gomplate.ca@3.11.4
      - run: gomplate -d adopters=./data/adopters.yaml -f templates/adopters.md -o docs/project/adopters.md
      - run: mkdocs gh-deploy --force
