name: PR Validation

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: pip install -e .

      - name: Install gomplate
        uses: pkgxdev/setup@v1
        with:
          +: gomplate.ca@3.11.4

      - name: Generate dynamic content
        run: gomplate -d adopters=./data/adopters.yaml -f templates/adopters.md -o docs/project/adopters.md

      - name: Test mkdocs build
        run: mkdocs build --strict

      - name: Validate generated site
        run: |
          if [ ! -d "site" ]; then
            echo "Error: site directory not generated"
            exit 1
          fi
          if [ ! -f "site/index.html" ]; then
            echo "Error: index.html not generated"
            exit 1
          fi
          echo "✓ Documentation build successful"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Setup Pre-commit
        run: pip install pre-commit

      - name: Run Pre-commit
        run: pre-commit run --all-files

  commit-msg-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all the history of PR commits

      - name: Setup Pre-commit
        run: pip install pre-commit

      - name: Run Pre-commit
        run: pre-commit run --hook-stage manual pr-commit-lint --all-files
        env:
          FROM: ${{ github.event.pull_request.base.sha }}
          TO: ${{ github.event.pull_request.head.sha }}
